spring:
    application:
        name : config-client
    cloud:
        config:
          #配置文件
          profile: test
          #配置服务地址
          uri: http://localhost:8888/
          #GitHub分支
          label: master
server:
    port: 8088

management:
    security:
        enabled: false

