server:
  port: 8081

#指定微服务的名称后续在调用的时候只需要使用该名称就可以进行服务的访问
spring:
  application:
    name: eureka-provider

eureka:
  client:
    serviceUrl:
      # 服务注册和发现地址
      defaultZone: http://localhost:8761/eureka/